# Generated by Django 5.0.6 on 2025-09-23 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_blockeduser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='registration_date',
        ),
    ]
